<a href="https://colab.research.google.com/github/SasiwimonV/Basicprog_DataViz65/blob/main/Recap4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Matrix Slicing

In [10]:
import numpy

In [11]:
list_a = [[2,4,5],[1,2,3],[9,8,7],[3,6,9]]
mat_a = numpy.array(list_a)
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [5]:
import numpy as np

In [6]:
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b = np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

##Quiz2

1.slice ค่าลบออกมานาก mat_b

2.slice [1,2,3] จาก mat_a

3.slice [[1,3],[9,7],[3,9]] ออกมาจาก mat_b

In [7]:
#ข้อ1
mat_b [:5,:2]

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

In [12]:
#ข้อ2
mat_a[1:2,:4]

array([[1, 2, 3]])

In [13]:
#ข้อ3
mat_b[1:4,2:5:2]

array([[1, 3],
       [9, 7],
       [3, 9]])

##HW1

เขียน function แสดงความต่างของเวลา (Quiz1) โดย input อยู่ในรูปแบบ '09:11:50 - 12:30:15'

และทดลองรัน

'09:11:50 - 12:30:15'

'13:41:07 - 20:00:18'

'00:00:00 - 23:59:59'


In [5]:
def print_time(mytime):
    start=mytime.split("-")  
    time1=start[0] 
    sp_time1=time1.split(":") 
    time2=start[1] 
    sp_time2=time2.split(":") 
    x1 = (int(sp_time1[0])*3600)+(int(sp_time1[1])*60)+int(sp_time1[2])
    x2 = (int(sp_time2[0])*3600)+(int(sp_time2[1])*60)+int(sp_time2[2])
    time3 = x2-x1
    print(f'{time1}-{time2} ความต่างของเวลา = {time3} วินาที')

In [6]:
print_time("09:11:50-12:30:15")

09:11:50-12:30:15 ความต่างของเวลา = 11905 วินาที


In [3]:
print_time("13:41:07 - 20:00:18")

13:41:07 - 20:00:18 ความต่างของเวลา = 22751 วินาที


In [4]:
print_time("00:00:00 - 23:59:59")

00:00:00 - 23:59:59 ความต่างของเวลา = 86399 วินาที
